esphome:
  name: comfoairq450
  friendly_name: "Comfoair Q450"
  area: "Technical Room"
  platform: esp32
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

logger:


ota:
  password: !secret ota_password
  platform: esphome


external_components:
  - source: github://vekexasia/comfoair-esp32
    components: [ comfoair ]

comfoair:  
